### ISSUE TITLE
Update terraform generator for v2 of terraform-cloudgov

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/rails-template#124]
## Story

As a ***rails dev***,
I would like to ***utilize the new terraform-cloudgov modules***,
So that I can ***have the latest and greatest IaC***

## Solution

```[tasklist]
### Tasks
- [x] refactor app module into a single module + per-env variables files
- [x] update modules to use v2
- [x] update bootstrap to use v2 and get rid of the need for service accounts
- [x] move app deployment into terraform
```

## Acceptance Criteria

- [x] app deployment fully controlled by terraform
- [x] easy feature-branch deploys
