### ISSUE TITLE
Investigate if thruster is compatible with cloud.gov

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/rails-template#126]
## Story

As a ***devops engineer***,
I would like to ***see if thruster will improve performance within cloud.gov***,
So that I can ***have the fastest app performance***

## Solution

```[tasklist]
### Tasks
- [x] Investigate if thruster is even compatible with running in the ruby_buildpack
- [x] Update railsrc to enable thruster by default
```

## Acceptance Criteria

- [x] New apps include thruster support out of the box

**Comment by rahearn** [comment]
https://github.com/basecamp/thruster
